services:
  keycloak:
    container_name: sachin-keycloak.openid-provider
    image: quay.io/keycloak/keycloak:26.0
    command:
    - start-dev
#    - --import-realm
    ports:
    - "8080:8080"
    volumes:
    - keycloak:/opt/keycloak/data/
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
      KC_PROXY_HEADERS: forwarded
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
#      KC_HTTP_PORT: 8080
#      KC_HTTP_HOST: 0.0.0.0
#      KC_HOSTNAME: http://localhost:8080
#      KC_HOSTNAME_ADMIN: http://localhost:8080
#      KC_HOSTNAME_STRICT: true
      KC_HTTP_RELATIVE_PATH: /auth
      PROXY_ADDRESS_FORWARDING: "true"
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_LOG_LEVEL: WARN
    extra_hosts:
    - "host.docker.internal:192.168.1.66"
    healthcheck:
      test: ['CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:8080/auth/health/live']
      interval: 5s
      timeout: 5s
      retries: 20
#  opendj:
#    image: openidentityplatform/opendj:4.9.4
#    container_name: opendj
#    ports:
#      - 11389:1389
#      - 4445:4444
#    environment:
#      - ROOT_USER_DN=cn=Directory Manager
#      - ROOT_PASSWORD=secret
#      - BASE_DN=dc=spring6recipes,dc=com
#    restart: always
  openldap:
    image: bitnami/openldap:2.6.10
    container_name: openldap
#    entrypoint: [ "/opt/bitnami/openldap/01-enable-dynlist.sh" ]
    ports:
      - '11389:1389'
      - '11636:1636'
    environment:
      - LDAP_ROOT=dc=spring6recipes,dc=com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=secret
      - LDAP_CUSTOM_LDIF_DIR=/opt/bitnami/openldap/custom_ldif
      - LDAP_CUSTOM_SCHEMA_DIR=/opt/bitnami/openldap/custom_ldif
    # full admin DN that the OpenLDAP server will create and recognize will be cn=admin,dc=spring6recipes,dc=com
    restart: always
    volumes:
      - ./ldif-schemas:/opt/bitnami/openldap/custom_ldif
#      - ./init-scripts/01-enable-dynlist.sh:/opt/bitnami/openldap/01-enable-dynlist.sh
      - ./init-scripts:/docker-entrypoint-initdb.d
volumes:
  keycloak:
    external: true
    name: keycloak-spring-boot-example_keycloak
