spring:
  profiles:
    active:
      default
  application:
    name: gateway-server
#  config:
#    import: "optional:configserver:http://configs:8888"
encrypt:
  key: APODNU3093r2rbjzxcn09u213asdhy08WRFH
#logging:
#  level:
#    com.netflix: WARN
#    org.springframework.web: WARN
#    com: DEBUG

#server:
#  port: 8072
